apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: senthilapi

resources:
  - ../../base

images:
  - name: ghcr.io/s3nthilg0pal/senthil-api
    newName: ghcr.io/s3nthilg0pal/senthil-api
    newTag: 6ab409b6ca75a95aa10cf8ec6605f5ef2e496a4a

patches:
  - target:
      kind: Deployment
      name: senthilapi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
