apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: senthilapi

resources:
  - ../../base

images:
  - name: ghcr.io/s3nthilg0pal/senthil-api
    newName: ghcr.io/s3nthilg0pal/senthil-api
    newTag: 1957693cfd9b3d92e618753fd11da37bc9fb5925

patches:
  - target:
      kind: Deployment
      name: senthilapi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
