apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: senthilapi

resources:
  - ../../base

images:
  - name: ghcr.io/s3nthilg0pal/senthil-api
    newName: ghcr.io/s3nthilg0pal/senthil-api
    newTag: a74ac4f46f6741b4ef07b3c2e6aaebcd773bacd0

patches:
  - target:
      kind: Deployment
      name: senthilapi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
