apiVersion: v1
kind: Secret
metadata:
  name: senthilapi-secrets
  namespace: senthilapi
type: Opaque
stringData:
  Auth__ApiKey: CHANGE_ME_API_KEY
  ConnectionStrings__Database: CHANGE_ME_CONNECTION_STRING
